name: Train Llama

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install huggingface
        run: |
          pip install huggingface-hub

      # - name: Send the build image
      #   run: |
      #     python push.py

      - name: Send the run image
        run: |
          python run.py
