name: Train Llama

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: nroggendorff
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag the Docker image
        run: |
          docker build . \
            -f Dockerfile \
            --build-arg HF_TOKEN=${HF_TOKEN} \
            -t nroggendorff/train-llama:latest

      - name: Push the Docker image
        run: |
          docker push nroggendorff/train-llama:latest
